/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbmspages;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class admin_addbills extends javax.swing.JFrame {

    /**
     * Creates new form admin_addbills
     */
    public admin_addbills() {
        initComponents();
        Connect();
        DefaultTableModel dtm = (DefaultTableModel)aatable.getModel();
        
        try {
            rs1 = pst1.executeQuery("select * from paid_list");
            rs = pst.executeQuery("select * from pending_list where pendingbool=1");
            while(rs.next() && rs1.next()){
                dtm.addRow(new Object[]{rs.getString("no"),rs.getString("cid"),rs.getString("areaid"),rs.getString("pldate"),rs.getString("pendingbool"),rs1.getString("pendingdue")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin_addbills.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    Connection con;
    Statement pst,pst1;
    
    ResultSet rs,rs1;
    
       
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/water_management","root","Kausthubh1");
            pst = con.createStatement();
            pst1 = con.createStatement();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frontpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aacid = new javax.swing.JTextField();
        aapdue = new javax.swing.JTextField();
        aadd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        aatable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("CUSTOMER ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 153, -1, -1));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 43, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("DUE DATE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 234, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("PENDING DUE:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 315, -1, -1));

        aacid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aacidActionPerformed(evt);
            }
        });
        jPanel1.add(aacid, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 153, 140, -1));

        aapdue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aapdueActionPerformed(evt);
            }
        });
        jPanel1.add(aapdue, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 315, 140, -1));
        jPanel1.add(aadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 234, 140, -1));

        aatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BILL NO", "CUSTOMER ID", "AREA ID", "DUE DATE", "STATUS", "AMOUNT"
            }
        ));
        jScrollPane1.setViewportView(aatable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 140, 552, 473));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbmspages/Add a heading (1).png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        close();
        admin ad = new admin();
        ad.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = aacid.getText();
        String due = aadd.getText();
        String dueam = aapdue.getText();
        try {
            rs = pst.executeQuery("select areaid from customer where cid='"+id+"'");
            rs.next();
            String aid = rs.getString("areaid");
            pst.executeUpdate("INSERT INTO `water_management`.`pending_list` (`cid`, `areaid`, `pldate`, `pendingbool`) VALUES ('"+id+"', '"+aid+"', '"+due+"', '1')");
            rs = pst.executeQuery("select no from pending_list where cid ='"+id+"' and areaid='"+aid+"'and pldate='"+due+"'");
            rs.next();
            String numb = rs.getString("no");
            pst.executeUpdate("INSERT INTO `water_management`.`paid_list` (`no`, `areaid`, `cid`, `pendingdue`) VALUES ('"+numb+"', '"+aid+"', '"+id+"', '"+dueam+"')");
            aacid.setText("");
            aadd.setText("");
            aapdue.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(admin_addbills.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        DefaultTableModel dtm = (DefaultTableModel)aatable.getModel();
        dtm.setRowCount(0);
        try {
            rs1 = pst1.executeQuery("select * from paid_list");
            rs = pst.executeQuery("select * from pending_list where pendingbool=1");
            while(rs.next() && rs1.next()){
                dtm.addRow(new Object[]{rs.getString("no"),rs.getString("cid"),rs.getString("areaid"),rs.getString("pldate"),rs.getString("pendingbool"),rs1.getString("pendingdue")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin_addbills.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aacidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aacidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aacidActionPerformed

    private void aapdueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aapdueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aapdueActionPerformed
     public void close(){
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_addbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_addbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_addbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_addbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_addbills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aacid;
    private javax.swing.JTextField aadd;
    private javax.swing.JTextField aapdue;
    private javax.swing.JTable aatable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
